---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # 도커 허브 로그 인
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 도커 허브 로그 아웃
      - name: Checkout
        uses: actions/checkout@v2
      # 장고 프로젝트 test
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      # flake8을 이용한
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
